name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  validate-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@v12
      continue-on-error: true
      with:
        output_format: cli, json
        output_file_path: console,results.json
        directory: .

    - name: Publish security report to artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: checkov-report
        path: results.json

  plan:
    runs-on: ubuntu-latest
    needs: validate-and-scan
    permissions:
      id-token: write # Require write permission to Fetch an OIDC token.
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.2

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var=db_password=${{ secrets.DB_PASSWORD }} -out ./infraPlan

    - name: Post PR comment
      uses: borchero/terraform-plan-comment@v2
      with:
        token: ${{ github.token }}
        planfile: ./infraPlan

    - name: Upload plan
      uses: actions/upload-artifact@v4
      with:
        name: plan
        path: ./infraPlan